package co.edu.unicauca.cuychair.gui.views;

import co.edu.unicauca.cuychair.gui.views.panels.ConferencePanel;
import co.edu.unicauca.cuychair.gui.views.panels.PapersPanel;
import co.edu.unicauca.cuychair.gui.views.panels.ReviewPapersPanel;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author Frdy
 */
public class MainView extends javax.swing.JFrame {

    private static SelectedView selectedView = null;

    /**
     * Creates new form NewJFrame
     */
    public MainView() {        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public MainView(String viewId) {
        SelectedView selection = SelectedView.valueOf(viewId);
        initComponents();
        setLocationRelativeTo(null);        
        selectView(selection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        InfoPanel = new javax.swing.JPanel();
        userIconLabel = new javax.swing.JLabel();
        userInfoLabel = new javax.swing.JPanel();
        mailLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        navigationPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        headerPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userIcon.png"))); // NOI18N
        InfoPanel.add(userIconLabel);

        userInfoLabel.setLayout(new javax.swing.BoxLayout(userInfoLabel, javax.swing.BoxLayout.Y_AXIS));

        mailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        mailLabel.setText("user@mail.com");
        userInfoLabel.add(mailLabel);

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        usernameLabel.setText("Nombre de Usuario");
        userInfoLabel.add(usernameLabel);

        InfoPanel.add(userInfoLabel);

        jButton1.setText("Ver Conferencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        navigationPanel.add(jButton1);

        jButton2.setText("Articulos Enviados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        navigationPanel.add(jButton2);

        jButton3.setText("Revision de Articulos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        navigationPanel.add(jButton3);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        viewPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(viewPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectView(SelectedView.CONFERENCE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectView(SelectedView.PAPERS);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectView(SelectedView.REVIEW_PAPERS);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    public void selectView(SelectedView selectedView) {        
        CardLayout cardLay = (CardLayout) viewPanel.getLayout();
        if (!selectedView.hasBeenGotted()) {
            viewPanel.add(selectedView.getPanel(), selectedView.getId());
        }
        cardLay.show(viewPanel, selectedView.getId());
        this.selectedView = selectedView;
        
        viewPanel.validate();        
        
        // cambia el titulo de la ventana
        this.setTitle(selectedView.getId());
        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JPanel userInfoLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Enum to manage the view selected  <br>
     * this implements lazy loading with the companion of the function `selectView()`
     */
    private enum SelectedView {
        CONFERENCE("Conference"),
        PAPERS("Papers"),
        REVIEW_PAPERS("ReviewPapers");
        
        private final String id;
        private JPanel panel; // panel seleccionado
        
        private static Map<String, JPanel> panelsGotted = new HashMap<>(3);

        private SelectedView(String id) {
            this.id = id;
            panel = null;                 
        }
        
        public JPanel getPanel() {
            if (panelsGotted.containsKey(id)) return panel;
            switch (id) {
                case "Conference" -> panel = new ConferencePanel();
                case "Papers" -> panel = new PapersPanel();
                case "ReviewPapers" -> panel = new ReviewPapersPanel();
            }
            panelsGotted.put(id, panel);
            return panel;
        }
        
        public boolean hasBeenGotted() {
            return panelsGotted.containsKey(id);
        }
        
        public String getId() {
            return id;
        }
    }

}
