package co.edu.unicauca.cuychair.gui.views.panels;

import java.awt.Color;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author Frdy
 */
public class ConferenceCardPanel extends javax.swing.JPanel {
    
    private String title;
    private String description;
    public final static int WIDTH = 250;
    private static AtomicInteger counter = new AtomicInteger();
    
    /**
     * Creates new form ConferenceCardPanel
     */
    public ConferenceCardPanel(String title, String description) {
        this.title = title;
        this.description = description;
        initComponents();        
        additionalInitComponent();
    }
    
    public void additionalInitComponent() {
        titleLabel.setText(title);
        descriptionLabel.setText(description);
        Integer number = counter.getAndIncrement()*100;
        //this.setBackground(new Color(number%255, (number/255) % 255, (number/(255*255)%255)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        descriptionLabel = new co.edu.unicauca.cuychair.gui.views.controllers.JMultilineLabel();

        setPreferredSize(new java.awt.Dimension(250, 199));

        titleLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Conference Title");

        jButton1.setText("Ver más");

        jButton2.setText("Mandar Articulo");

        descriptionLabel.setColumns(20);
        descriptionLabel.setRows(5);
        descriptionLabel.setText("[Nombre de la Conferencia] es un evento anual que reúne a expertos, profesionales y entusiastas de [tema o industria] para compartir conocimientos, descubrir las últimas tendencias y fomentar la colaboración. Durante [número de días] días, los asistentes podrán participar en una variedad de actividades, como presentaciones magistrales, sesiones interactivas, paneles de discusión y talleres prácticos, diseñados para profundizar en temas clave de [tema o industria].\n\nCon una selección de ponentes reconocidos a nivel nacional e internacional, esta conferencia ofrece una oportunidad única para aprender de los líderes de opinión y pioneros del sector. Además, los asistentes podrán expandir su red de contactos a través de sesiones de networking y eventos sociales, favoreciendo la creación de relaciones duraderas y oportunidades de colaboración.\n\nNo importa si eres un profesional experimentado, un investigador académico o alguien que recién comienza en el campo; [Nombre de la Conferencia] tiene algo para todos. Únete a nosotros para una experiencia enriquecedora que contribuirá a tu crecimiento profesional y personal en [tema o industria].\n\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(titleLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );

        titleLabel.getAccessibleContext().setAccessibleDescription("Conference Title");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.edu.unicauca.cuychair.gui.views.controllers.JMultilineLabel descriptionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
